### ISSUE TITLE
有团队组件，但调用 getTeamLibraryAsync 获取仍是空数组

### ISSUE THREAD

**Issue by kiner-tang** [mastergo-design/html-to-mastergo#39]
**描述问题**
有团队组件，但调用 getTeamLibraryAsync 获取仍是空数组

**复现步骤**
重现此问题的步骤:
1. 使用 `const tl = await mg.getTeamLibraryAsync();` 获取团队库并打印到控制台
2. 查看控制台输出
3.
4.

**期望结果**
可以获取到团队库中的组件信息和样式信息

**截图**
<img width="699" alt="image" src="https://github.com/mastergo-design/plugin-typings/assets/10286961/c152d044-4ee9-4aa1-a554-8f109a3f5bcf">
![image](https://github.com/mastergo-design/plugin-typings/assets/10286961/c9e97cd1-88cd-4ac9-a66b-e3475d078f9e)
<img width="252" alt="image" src="https://github.com/mastergo-design/html-to-mastergo/assets/10286961/76d97b06-2052-4827-ae9c-6f673d696bb2">

**其他内容**
在此处添加有关问题的任何其内容.

**Comment by fake-car** [comment]
看了一下左侧应该没有订阅团队库，订阅了以后再去调用就能拿得到

**Comment by kiner-tang** [comment]
本地的组件库无法获取吗？尝试了一下，订阅公共组件库后可以获取。如果想要订阅本地的组件库，要怎么操作

**Comment by fake-car** [comment]
> 本地的组件库无法获取吗？尝试了一下，订阅公共组件库后可以获取。如果想要订阅本地的组件库，要怎么操作

插件没有订阅组件库的接口，需要在画布内取手动操作

**Comment by kiner-tang** [comment]
好的，感谢解答
