### ISSUE TITLE
不实例化的情况下如何获取组件的封面等详细信息

### ISSUE THREAD

**Issue by kiner-tang** [mastergo-design/html-to-mastergo#42]
想要实现一个插件，在插件中智能推荐团队库组件，但通过 `getTeamLibraryAsync` 获取的组件信息仅有名称、ukey之类的简单信息， 不实例化的情况下如何获取组件的封面等详细信息

**Comment by fake-car** [comment]
目前已经对团队库的组件字段增加cover和宽高信息，可以在控制台调用查看
