### ISSUE TITLE
有办法获取系统 粘贴板的内容吗

### ISSUE THREAD

**Issue by March-Wind** [mastergo-design/html-to-mastergo#47]
**描述问题**
我想在插件中获取系统的粘贴板里的内容。调用 window.navigator.clipboard.readText()时，说没有readText方法，发现在clipboard是undefined.

**期望结果**
在插件中获取系统的粘贴板里的内容

**Comment by fa3eng** [comment]
监听 copy 和 paste 事件，里面的 event 可以访问到剪切板
